version: '3'

services:

  backend:
    container_name: backend
    build:
      context: ./django
    command: gunicorn core.wsgi --bind 0.0.0.0.8000
    ports:
      - '8000:8000'

  frontend:
    container_name: frontend
    build:
      context: ./react
    volumes:
      - react_build:/react/build
    
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - '80:8080'
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
      - react_build:/var/www/react
    depends_on:
      - backend
      - frontend

volumes:
  react_build